services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    container_name: sec-keycloak
    hostname: keycloak
    command: start-dev -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/tmp/import -Dkeycloak.migration.strategy=OVERWRITE_EXISTING --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
    restart: no
    ports:
      - 8092:8080
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
      - ./keycloak/configuration:/tmp/import
    environment:
      TZ: Europe/Berlin
      KC_PROXY_HEADERS: forwarded
      KC_HTTPS_PORT: 8092
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB_URL: jdbc:h2:file:~/data/h2/keycloakdb;AUTO_SERVER=TRUE;NON_KEYWORDS=VALUE
      KC_FEATURES: transient-users

  mongodb:
    image: mongo:latest
    container_name: sec_mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    image: security-gateway:${PROJECT_VERSION}
    container_name: sec-gateway
    hostname: gateway
    ports:
      - 8095:8095
    depends_on:
      - resource-server
    environment:
      RESOURCE_SERVER_URL: ${RESOURCE_SERVER_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}

  resource-server:
    build:
      context: .
      dockerfile: ./resource-server/Dockerfile
    image: security-resource-server:${PROJECT_VERSION}
    container_name: sec-resource-server
    hostname: resource-server
    ports:
      - 8090:8090
    depends_on:
      - mongodb
      - keycloak
    environment:
      KEYCLOAK_URL: ${KEYCLOAK_URL}

  mysql:
    profiles:
      - openfga
    image: mysql:8
    container_name: sec-openfga-mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=openfga
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 5
    networks:
      - openfga

  migrate:
    profiles:
      - openfga
    depends_on:
      mysql:
        condition: service_healthy
    image: openfga/openfga:latest
    container_name: sec-openfga-migrate
    command: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=mysql
      - OPENFGA_DATASTORE_URI=root:secret@tcp(mysql:3306)/openfga?parseTime=true
    networks:
      - openfga

  openfga:
    profiles:
      - openfga
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: sec-openfga
    hostname: openfga
    environment:
      - OPENFGA_DATASTORE_ENGINE=mysql
      - OPENFGA_DATASTORE_URI=root:secret@tcp(mysql:3306)/openfga?parseTime=true
      - OPENFGA_LOG_FORMAT=json
    command: run
    networks:
      - openfga
      - security
    ports:
      # Needed for the http server
      - "8080:8080"
      # Needed for the grpc server (if used)
      - "8081:8081"
      # Needed for the playground (Do not enable in prod!)
      - "3000:3000"

volumes:
  mongodb_data:
  keycloak_data:

networks:
  openfga:
  security:
  default:
    name: security