spring:
  profiles:
    active: openfga
  security:
    oauth2:
      resource server:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8092}/realms/Test-Realm/protocol/openid-connect/certs
          principal-claim-name: preferred_username
  docker:
    compose:
      enabled: false
      file: compose.yml
  application:
    name: Resource Server
  data:
    mongodb:
      database: testdb
      uri: ${DATABASE_URL:mongodb://user:test@localhost:27017}
server:
  port: 8090
logging:
  level:
    org:
      springframework:
        security: warn
    root: info