spring:
  docker:
    compose:
      enabled: false
      file: compose.yml
  application:
    name: Resource Server
  data:
    mongodb:
      database: testdb
      uri: mongodb://user:test@localhost:27017
server:
  port: 8090